language: ruby

sudo: false

#services:
#  - docker

before_install:
#  - gem update --system
#  - gem --version
#  - rvm use default
#  - rvm repair wrappers

install:
- ./gitops/prepare.sh

script:
- ./gitops/deploy.sh
